### ISSUE TITLE
Overly complex code?

### ISSUE THREAD

**Issue by CoDEmanX** [ljharb/node-is-arrow-function#1]
[Rob posted](http://robcee.net/2013/fat-arrow-functions-in-javascript/#comment-1106) a very simple solution to figure out whether a function is an arrow function or not:

    function isArrowFunction(fn) {
        try {
            new fn();
        } catch(e) {
            return true;
        }
        return false;
    }

For arrow functions, the exception **...is not a constructor** is raised for `new ()=>{}`,
but not `new function(){}` or `new new Function()`.

I verified it working in iojs 1.0.4 with `--harmony_arrow_functions` and in Firefox.

There should probably be an additional `typeof` check to ensure it's a function at all.

**Comment by ljharb** [comment]
```js
var Foo = function bar() {
  if (this instanceof bar) { throw new Error('not really an arrow function'); }
}
```

**Comment by ljharb** [comment]
I'll add a typeof check though for an early exit.

**Comment by CoDEmanX** [comment]
You are right, you would need to run your own code in a closure to avoid changes to global objects and the like.

But what about this:

    (()=>{}).hasOwnProperty("prototype") // false
    (function(){}).hasOwnProperty("prototype") // true

**Comment by ljharb** [comment]
I'd be concerned that ES6 class methods of a "class" that extends null would also report a false positive.

**Comment by CoDEmanX** [comment]
Static methods do have a prototype, as long as they are no arrow functions:

    "use strict"; class X {}

    X.foo = function(){ return "bar"}
    X.foo.hasOwnProperty("prototype") // true

    X.moo = ()=>"moo"
    X.moo.hasOwnProperty("prototype") // false

Methods don't, but you can't seem to access them via the class from outside. It has to be an instance of the class to get a false positive:

    "use strict"; class X {
        foo(){}
    }
    X.foo // undefined

    x = new X();
    x.foo.prototype // sadly undefined

BTW: all built-in functions will give false positives as well, as they don't have `prototype`.

**Comment by gajus** [comment]
See http://stackoverflow.com/q/34244183/368691 for a discussion regarding the best approach to determine if function is an arrow function.

I should have checked if there is an existing NPM package before writing this, https://github.com/gajus/is-arrow-function.

**Comment by ljharb** [comment]
@gajus your module will give a false negative if i pass it `() => { /* function */ }`, and your `isFunction` check will fail in an ES6 environment with `Symbol.toStringTag`.

**Comment by gajus** [comment]
@ljharb The first one is a valid bug (fixed https://github.com/gajus/is-arrow-function/commit/1aee4951df58633027fd06ec0a7cf2dd601d3207). The second observation is just nonsensical. If someone has overwritten `Symbol.toStringTag` he is asking for a trouble.

**Comment by ljharb** [comment]
None the less, the purpose of an "is foo" function is to be robust against any user action. if `{[Symbol.toStringTag]: 'Function', toString: () => '() => {}'}` reports as an arrow function, then your code is broken.
